name: Matrix Demo

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display Build Information
        run: |
          echo "Operating System: ${{ matrix.operating-system }}"
          echo "Node Version: ${{ matrix.node-version }}"
          node --version
